[tool.black]
line-length = 88
target-version = ['py38'] 

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["marshmallow", "pytest", "ratelimit", "requests", "requests_mock", "setuptools"]

[tool.coverage.run]
source = ["mokkari"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = ["--cov=mokkari/", "-n 3"]
